"""
This type stub file was generated by pyright.
"""

import logging
import os
import platform
import subprocess

log = ...
_RASPBERRY_PI_MACHINES = ...
def pv_library_path(relative: str = ...) -> str:
    ...

def pv_model_path(relative: str = ...) -> str:
    ...

def pv_keyword_files_subdir(): # -> Literal['mac', 'linux', 'raspberry-pi', 'windows']:
    ...

def pv_keyword_paths(relative: str = ...) -> dict:
    ...

