from typing import Any, Optional

# Minimal stubs for common pytesseract functions used in this project.
def image_to_string(image: Any, lang: Optional[str] = ..., config: Optional[str] = ...) -> str: ...
def image_to_data(image: Any, lang: Optional[str] = ..., config: Optional[str] = ...) -> str: ...
def image_to_boxes(image: Any, lang: Optional[str] = ..., config: Optional[str] = ...) -> str: ...
def image_to_osd(image: Any, lang: Optional[str] = ..., config: Optional[str] = ...) -> str: ...

# Optional: expose any attributes you use (e.g., pytesseract.pytesseract_cmd)
pytesseract_cmd: str